# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Java CI
on:
  push:
    branches:
    - 'master'
    - 'snapshot/**'
    - 'releases/**'
    paths:
    - 'src/**'
    - 'pom.xml'
    - '.github/workflows/*'
  # release:
  #   types: [published, created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy to Github Package Registry
      # https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${GITHUB_CONTEXT}"
        mvn deploy -Dmaven.test.skip=true --settings .github/workflows/maven-settings.xml --file pom.xml
