# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Java CI
on:
  push:
    branches:
    - 'master'
    - 'snapshot/**'
    - 'releases/**'
    paths:
    - 'src/**'
    - 'pom.xml'
  # release:
  #   types: [published, created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package -Dmaven.test.skip=true --file pom.xml
  deploy:
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - name: Deploy to Github repository
      # https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn deploy -Dmaven.test.skip=true --file pom.xml
